name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html

    reverb:
        build:
            context: ./docker
        env_file: .env
        environment:
            # Bind inside container
            REVERB_HOST: 0.0.0.0
            REVERB_PORT: 8080
            REVERB_PUBLIC_HOST: localhost
            REVERB_PUBLIC_PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        command: sh -lc "php artisan reverb:start --host=0.0.0.0 --port=8080"

    worker:
        build:
            context: ./docker
        depends_on:
            - app
            - redis
            - mysql
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        command: sh -lc "php artisan queue:work --queue=default --sleep=1 --tries=2"

    scheduler:
        build:
            context: ./docker
        depends_on:
            - app
            - redis
            - mysql
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        command: sh -lc "php artisan schedule:work"

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
